### ISSUE TITLE
frotend didn't show the logs

### ISSUE THREAD

**Issue by nextvirus** [SigNoz/signoz-otel-collector#122]
I use os.Stat().Size() fuction to see the file log . The log size is rasing
![23b56eee5a4a084465425933f23cb0f](https://user-images.githubusercontent.com/36720504/227764794-a965d9a3-535a-4fe6-8f85-8e54827f21aa.png)
But when i watch the frontend log dashboard, these logs don't show the page.
![4e3605266df9e0787dc2b2abf2cc01b](https://user-images.githubusercontent.com/36720504/227765126-19229461-c2fa-414d-b870-4b0e88c09db7.png)

**Comment by nityanandagohain** [comment]
Please share your otel-collector config and how you are collecting your logs
