### ISSUE TITLE
Update components to include latest semconv changes for remote host

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#15]
Bunch of attributes have been changed in this release https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.13.0. We should update the processor/exporter component to cover them as well.

**Comment by makeavish** [comment]
@ankitnayan 
GraphQL semantic conventions have been added: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/graphql.md

Should we also add GraphQL operation to with current SigNoz operation attribute? Do we need to add support for GraphQL separately? 
cc: @pranay01
