### ISSUE TITLE
move the schema migration out of collector

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#156]
Running multiple replicas of collectors creates issues, as no atomic lock migration is in place. Some potential options
1. Use a standalone migration repo/image
2. Use the init scripts of ClickHouse

**Comment by nityanandagohain** [comment]
With multiple clickhouse ditry can be resoved by deleting both `schema_migrations` and `logs_attribute_keys` table.

**Comment by ankitnayan** [comment]
>Use the init scripts of ClickHouse

we do not need to restart clickhouse for migrations to apply. If we use init scripts of clickhouse, we would have to restart clickhouse whenever we apply migrations

https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/

**Comment by ELLIOTTCABLE** [comment]
Oof, yeah, being unable to safely run multiple collectors in parallel is a bit of an issue for us.

I think, for the moment, then, our only option is to run `signoz-otel-collector` as a 'thin', ingest-only instance on a single box; and have our multiple non-forked `otel-collector` instances feed that "thin" ingestor over OTLP HTTP or something; have the non-forked instances perform any batching/aggregation/transformation … hrm.

**Comment by ankitnayan** [comment]
When we move out, we can also look to support templating of `cluster` name as requested in https://github.com/SigNoz/signoz-otel-collector/issues/180

**Comment by ankitnayan** [comment]
@ELLIOTTCABLE this is in progress and should be released soon
