### ISSUE TITLE
Why log attributes doesn't use Map to store in Clickhouse

### ISSUE THREAD

**Issue by mioyui88** [SigNoz/signoz-otel-collector#160]
I see the log table has columns named `attributes_string_key` and  `attributes_string_value`. And there doesn't add INDEX to speed search sql such as " select body from logs where attributes_string_value[indexOf(attributes_string_key, 'node')] = 'node-01' ".
 So why not use Map to store `attributes_string_key` and  `attributes_string_value`.

**Comment by srikanthccv** [comment]
V2 tables use map
