### ISSUE TITLE
Update Open telemetry contrib packages to 0.80.0

### ISSUE THREAD

**Issue by svsk417** [SigNoz/signoz-otel-collector#167]
Hi there, 
I have the requirement to display the system uptime in a dashboard. Therefore, I need at least 
github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerstatsreceiver v0.80.0
as stated in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md
As I see it, the policy is to build a release for every of these versions, since opentelemetry-collector-contrib does not adhire to semantic versioning. 
Therefore, it would be nice, if the versions 0.80, 0.81, 0.82 and 0.83 could be built :)

Greetings!

**Comment by svsk417** [comment]
In the meantime version 0.85.0 has been released.

**Comment by prashant-shahi** [comment]
@srikanthccv can you please look into this?

cc @ankitnayan

**Comment by srikanthccv** [comment]
Updating a version takes a lot of time because we need to go over all the versions CHANGELOG and ensure no breaking changes affect our customers. Will not be picking up this unless there is a strong reason other than uptime.
