### ISSUE TITLE
ADOT difference. 

### ISSUE THREAD

**Issue by chainhead** [SigNoz/signoz-otel-collector#169]
How is your collector different from say, ADOT https://aws-otel.github.io/ ?

- Exactly what is being open sourced?
- It appears, SigNoz is an integration of multiple open source products. What is the "smart" bit that SigNoz does over and above this integration?
- How does SigNoz position itself against other Prometheus Grafana vendors?

**Comment by srikanthccv** [comment]
>Exactly what is being open sourced?

Everything about our [distribution](https://opentelemetry.io/docs/concepts/distributions/) of OTEL Collector. From our schemas to components to our OpAMP support and everything in between. 

>It appears, SigNoz is an integration of multiple open source products. What is the "smart" bit that SigNoz does over and above this integration?

We are building a great observability product that is open-source and easy to self-host. We don't do anything "smart" for the sake of being "smart". And I am not sure what "integration" you are referring to.

>How does SigNoz position itself against other Prometheus Grafana vendors?

We don't.
