### ISSUE TITLE
[Usage][BugReport] Data is lost while using collector.

### ISSUE THREAD

**Issue by mioyui88** [SigNoz/signoz-otel-collector#170]
**Describe the bug**
I'm using collector to gather data from multi agents. Collector executing insert SQL into ClickHouse, and error like 'context deadline exceeded'.

**Steps to reproduce**
1. I use collector to gather data.
2. Collector executes insert into ClickHouse.

**What did you expect to see?**
1. SQL insertion successes.

**What did you see instead?**
1. error report like 'context deadline exceeded'.

**What version did you use?**
`v0.76.2`

**What config did you use?**
I will paste later.

**Environment**
OS: Centos 3.10.0
Compiler(if manually compiled): go 17.2

**Additional context**

**Comment by srikanthccv** [comment]
Try latest version and re-open if issue still exists
