### ISSUE TITLE
Why are num consumers set to 1 for exporter?

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#181]
https://github.com/SigNoz/signoz-otel-collector/blob/24cf1da3705cb791a3cb5061289631babe35b568/exporter/clickhouselogsexporter/config.go#L58-L64

Is there a reason behind fixing it one and not relying on the default queue size?

**Comment by srikanthccv** [comment]
The metrics exporter also has it, but it was initially based on the remote write, which has chronological requirements that don't apply anymore. I was wondering if this was overlooked or if there was some reason.

**Comment by srikanthccv** [comment]
@nityanandagohain, please help me understand why there is enforcedQueueSettings and why num_consumers is fixed to 1.

**Comment by nityanandagohain** [comment]
Hey, I see it was from first commit, I think this was just copied from the upstream as seen here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.48.0/exporter/clickhouseexporter/config.go

**Comment by nityanandagohain** [comment]
Don't see an issue with updating it, let me create a PR

**Comment by srikanthccv** [comment]
Use `exporterhelper.NewDefault{RetrySettings(), QueueSettings(), TimeoutSettings()}`

**Comment by nityanandagohain** [comment]
@srikanthccv using `exporterhelper.NewDefaultQueueSettings().NumConsumers` will solve the issue of default queueSize in https://github.com/SigNoz/signoz-otel-collector/blob/24cf1da3705cb791a3cb5061289631babe35b568/exporter/clickhouselogsexporter/config.go#L61

**Comment by srikanthccv** [comment]
While the issue is originally about num consumers, If there is no reason behind `enforcedQueueSettings`, let's get rid of it entirely and use the defaults for retry/timeout/queue settings.

**Comment by nityanandagohain** [comment]
cool.

**Comment by srikanthccv** [comment]
To be precise, my point was we have custom `QueueSettings` (which limits the config to one key but there are several options in the upstream queue settings), and there was no good reason for that. It doesn't make sense to keep these custom settings around in our code, and we should remove them entirely and rely on the settings from the `exporterhelper` and keep the same config defaults. This should be removed https://github.com/SigNoz/signoz-otel-collector/blob/285571690f5bbfab8a9ba6aac9059ee25b93156c/exporter/clickhouselogsexporter/config.go#L40-L44 and the `QueueSettings` here will be replaced with `exporterhelper.QueueSettings ` https://github.com/SigNoz/signoz-otel-collector/blob/285571690f5bbfab8a9ba6aac9059ee25b93156c/exporter/clickhouselogsexporter/config.go#L25-L37 and this will be updated with `c.QueueSettings ` https://github.com/SigNoz/signoz-otel-collector/blob/285571690f5bbfab8a9ba6aac9059ee25b93156c/exporter/clickhouselogsexporter/factory.go#L87-L96

**Comment by nityanandagohain** [comment]
Can you check once now ?
