### ISSUE TITLE
Update to v0.62.0

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#19]

**Comment by nityanandagohain** [comment]
* Support for converting attributes to int https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1666862826745589?thread_ts=1666095397.325379&cid=C01HWQ1R0BC
* `bodies` support in filter processor. https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1666220574043699?thread_ts=1666211639.085029&cid=C01HWQ1R0BC

**Comment by srikanthccv** [comment]
Apart from updating each component pdata model changes.

1. Update the minimum required SDK exporter version and client collector version with `opentelemetry-proto >= 1.15.0` https://github.com/open-telemetry/opentelemetry-collector/pull/5819
2. Breaking remote host semantic conventions https://github.com/open-telemetry/opentelemetry-specification/pull/2594
3. Host stats receiver doesn't have direction attribute, i.e., old value before breaking change (ex: `system.disk.operation_time.read` -> `system.disk.operation_time`)
4. `dockerstatsreceiver`: 
     - `container.cpu.usage.system` is not enabled by default.
     - config key change from `stats` to `metrics`
     - removal of all metrics to sensible metrics
5. Update `signozspanmetricsprocessor`
6. Update `prometheusremotewrite` exporter with bug fixes.

**Comment by makeavish** [comment]
We have upgraded to v0.63.0
So can we close this issue: @srikanthccv @nityanandagohain ?

**Comment by nityanandagohain** [comment]
Yeah we can close this
