### ISSUE TITLE
Upgrade path for upstream breaking changes till 0.88

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#224]
- httpcheckreceiver: now supports multiple targets and requires a list of targets

**Comment by srikanthccv** [comment]
@prashant-shahi 

there is a braking change in the kubeletstats receiver default config https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#v0870. Please check if this affects our metrics collection/alerts. 

And this https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#-breaking-changes--5

These are only things that found relevant to us. Please check if anything else breaks.

**Comment by prashant-shahi** [comment]
Tested 0.88 with SigNoz chart and k8s-infra chart => SigNoz Cloud.
