### ISSUE TITLE
GraalVM Native Executable Support?

### ISSUE THREAD

**Issue by korkutkose** [SigNoz/signoz-otel-collector#241]
Hi everyone,
A quick question. With all the examples provided, I can see that in order to collect metrics from java app, we need to invoke and run our apps with some JAVA_OPTS which means we do require JVM. 
As you may or may not know, it's now possible to create native executables for JAVA apps, thanks to GraalVM, which means there is no any need of JVM and JAVA_OPTS at runtime.
The question is that, is it possible to provide these metrics without invoking the tracing jar, maybe embedding it to apps or something else? We would like to use SigNoz, but I feel like it has not been supported for native executables as of today?
https://www.graalvm.org/latest/reference-manual/native-image/

**Comment by srikanthccv** [comment]
No, please see https://github.com/oracle/graal/issues/1065

**Comment by srikanthccv** [comment]
Closing this since the graal doesn't support agents yet

**Comment by ziyilin** [comment]
A new PR(https://github.com/oracle/graal/pull/8077) from GraalVM tries to support agent in native image.  It can work with Opentelemetry agent.
