### ISSUE TITLE
Not supporting all receivers from opentelemetry-collector-contrib.

### ISSUE THREAD

**Issue by TripathiVedant** [SigNoz/signoz-otel-collector#260]
eg. Receivers like [awscloudwatchmetricsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscloudwatchmetricsreceiver) are not yet accomodated.

**Comment by srikanthccv** [comment]
It's still in the development stage but if you are interested in using it feel free to send a pull request adding the receiver(s). You just need to update https://github.com/SigNoz/signoz-otel-collector/blob/main/components/components.go

**Comment by TripathiVedant** [comment]
Raised PR #263
