### ISSUE TITLE
Discard logs older than the retention period

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#272]
If an ingested log is older than the retention period skip it from getting ingested.

**Comment by nityanandagohain** [comment]
How do you think we should keep the TTL of the schema in memor. Like we can check it at the start of the collector and it will be populated to 15 days but if it is changed then it will still remain 15 days in the collector memory.

Or that should be fine ?

**Comment by srikanthccv** [comment]
This should be a very uncommon case. You can fetch the TTL at the start and only when you come across a timestamp that's before the retention period you can "refresh" the recentness of the TTL by fetching again. Let's do this only when the batch can potentially create an error and let the ClickHouse manage the TTL'ing old data. What I mean by that is If we only see old timestamp then it should be fine to insert it. But If we see more partitions than ClickHouse server is configured to handle then "refresh" the TTL. There maybe a simple way to do this.

**Comment by ankitnayan** [comment]
Shouldn't it be fine to discard all records older than `min(retention configured, 60)`? I am guessing this might be a problem again when TTL is set to say 1yr?

So, we ingest oldest 60 days data at max even if the retention is set to anything.

1. Fetch retention period
2. Check the oldest log record in the batch. If it's older than `min(retention configured, 60)` then reject. Fetch the retention period again


Assuming, retention period does not change often.

**Comment by srikanthccv** [comment]
That might work for the cloud given we have the control but we don't know what retention period OSS people set and we made it easy to change it from UI. While it doesn't often, there is no trigger to know if & when the setting is changed which requires us to check the TTL occasionally. This check should neither be too many times nor once at the start-up that it ignores the updated TTL setting. I think `min(retention configured, 60)` will be problematic for many people running outside the cloud.

**Comment by nityanandagohain** [comment]
Solution we are going with
* Check the error received from clickhouse
* If the error says that too many partitions then fetch the TTL from clickhouse and drop the older data.

---
If error occurs during retry directly drop the batch  or throw error ?

**Comment by srikanthccv** [comment]
The same error `Too many partitions for single INSERT block` shouldn't happen after you drop the data. Return error to the caller on retry error.
