### ISSUE TITLE
Usage collection data race condition when more than one clickhouse exporter is used in a signle pipeline

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz-otel-collector#280]
Usage collection data race condition when more than one clickhouse exporter is used in a signle pipeline

so if there are two clickhouse logs exporters `clickhouselogs/1`, `clickhouselogs/2`

----
**previously**
both used the same metric
signoz_logs_count{collector_id} = count of exporter 1 + count of exporter 2

and while exporting usage both exported the same data

----
**We needed to change it to**

signoz_logs_count{collector_id, exported_id_1} = count exporter 1 
signoz_logs_count{collector_id, exported_id_2 } = count exporter 2

and while exporting 
exporter 1 exports `signoz_logs_count{collector_id, exported_id_1} `
exporter 2 exports `signoz_logs_count{collector_id, exported_id_2 } `

**Comment by srikanthccv** [comment]
I don't understand the issue, please share some more detail and what is PR trying to fix.

**Comment by nityanandagohain** [comment]
@srikanthccv  I have updated the description

**Comment by nityanandagohain** [comment]
Yes there is an exporter id.

It didn't cause race condition previously because we had different kinds of exporter with single instance ex:- clickhouse logs, clickhouse traces

but when there are are two instances of the same type of exporter both of them considers each others value, this fix makes sure that for the same type of exporter each exports it's own value and not the other.
