### ISSUE TITLE
The initial value service.instance.id is overwritten and displayed as an hex encoded string

### ISSUE THREAD

**Issue by cedstrom** [SigNoz/signoz-otel-collector#283]
[See signoz #4388](https://github.com/SigNoz/signoz/issues/4338)

A change in the otel collector has caused the instance id to show up as a hex string rather than as the actual name of the service.

Potential fix is also included: https://github.com/sharpSteff/signoz-otel-collector/commit/e8005a542c67a16342ab4664f2c2876f0f8565fb

**Comment by cedstrom** [comment]
@srikanthccv, the regression seems to have been isolated to your commit: https://github.com/SigNoz/signoz-otel-collector/commit/d1dc659eae9eddf93c88bf567d4346f105601789.  Can you take a look?

**Comment by srikanthccv** [comment]
For the span metrics, the collector is the source that generates the metrics. The idea behind the `service.instance.id` is to introduce uniqueness and produce a unique time series from each metric generator. If this were not the case, two replicas of the signoz-otel-collector would produce an identical time series which would lead to incorrect results. I guess the ideal fix is to not replace the original `service.instance.id` but continue to use `signoz.collector.id` to guarantee single-write metric stream https://opentelemetry.io/docs/specs/otel/metrics/data-model/#single-writer
