### ISSUE TITLE
Question about the relationship to opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by greg-zund** [SigNoz/signoz-otel-collector#287]
Hi 
I'm a bit confused about the relationship of this collector to the [opentelemetry collector](https://github.com/open-telemetry/opentelemetry-collector-contrib). Both seem to have possibilities to export to clickhouse. However, there is no signoz exporter in the opentelemetry collector repo. Can someone point me to any documentation on this or compare the two? Is it possible to use the opentelemetry collector with signoz (with the clickhouse exporter)?

**Comment by srikanthccv** [comment]
This is called the distribution model https://opentelemetry.io/docs/concepts/distributions/.
