### ISSUE TITLE
unordered helm chart migrations fail horribly

### ISSUE THREAD

**Issue by svalaskevicius** [SigNoz/signoz-otel-collector#291]
3 days ago the helm chart was updated. both clickhouse version was updated and a migration using a new feature (quantilesDD) was run as part of the db migration.

except that k8s tried to run the db migration first, and failed (clickhouse was left unupgraded)

**Comment by svalaskevicius** [comment]
or maybe the issue is not that, but the fact that clickhouse was not updated by the helm chart and metrics table in v7 is using a new function not available in our clickhouse

**Comment by srikanthccv** [comment]
Please use the latest charts version `0.35.2` and check again.

**Comment by svalaskevicius** [comment]
yep, sorted. thanks!
