### ISSUE TITLE
Can not specify a cluster name for Clickhouse

### ISSUE THREAD

**Issue by chensunny** [SigNoz/signoz-otel-collector#306]
Can not specify a `cluster` name for Clickhouse。

Since we're using a self-built Clickhouse cluster, the DBA will specify the appropriate name(such as `default` ). 
So we can not use the name `cluster` cluster

https://github.com/SigNoz/signoz-otel-collector/blob/49769fd8f39e7313d1729977e31b25ebf23d1a01/exporter/clickhouselogsexporter/exporter.go#L47C2-L47C9

<img width="618" alt="image" src="https://github.com/SigNoz/signoz-otel-collector/assets/6245343/4e6b1787-efa2-412b-b789-3df2b075b394">

**Comment by srikanthccv** [comment]
The constant you linked to is not used anywhere in the code.

**Comment by srikanthccv** [comment]
https://github.com/SigNoz/signoz-otel-collector/pull/307

**Comment by srikanthccv** [comment]
Specifying your own cluster name is supported.
