### ISSUE TITLE
Use --cluster instead of --cluster-name in migrator command flag

### ISSUE THREAD

**Issue by git-hulk** [SigNoz/signoz-otel-collector#308]
Currently,  the otel collector is using the `--cluster-name` to pass the ClickHouse name, but the signoz query component is using `--cluster`. See:

[1] https://github.com/SigNoz/signoz-otel-collector/blob/main/cmd/signozschemamigrator/migrate.go#L41
[2] https://github.com/SigNoz/signoz/blob/develop/pkg/query-service/main.go#L54

Not sure if it sounds good to add an extra `--cluster` to keep consistent with the query component, or add an extra option `--cluster-name` in the query component?

I will be happy to submit a PR to resolve this if it sounds good.

**Comment by srikanthccv** [comment]
Let's change the query service arg to `--cluster-name`.

**Comment by git-hulk** [comment]
@srikanthccv Thank you! Will do it soon.
