### ISSUE TITLE
Question related to TLS for clickhousetraces exporter

### ISSUE THREAD

**Issue by somnusfish** [SigNoz/signoz-otel-collector#314]
Hi,

The sample deployment from signoz chart uses tcp for clickhousetraces, is there anyway to configure TLS for the exporter? If yes, could you provide an example on how to do that?

https://github.com/SigNoz/charts/blob/main/charts/signoz/values.yaml#L1912-L1914
```
datasource: tcp://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/?database=${CLICKHOUSE_TRACE_DATABASE}&username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}
        low_cardinal_exception_grouping: ${LOW_CARDINAL_EXCEPTION_GROUPING}
```

**Comment by srikanthccv** [comment]
This is the updated config https://github.com/SigNoz/charts/blob/main/charts/signoz/values.yaml#L1936. You would add `secure=true&skip_verify=true` to the connection string. 

Example

`tcp://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/${CLICKHOUSE_TRACE_DATABASE}?secure=true&skip_verify=true`
