### ISSUE TITLE
http2 frame too large error when sending file log over grpc 

### ISSUE THREAD

**Issue by yasingllu** [SigNoz/signoz-otel-collector#323]
This is my otel-collector-config on the client side

`receivers:
  filelog:
    include: [ /var/log/x/x.log ]
    start_at: end
processors:
  batch:
    send_batch_size: 1000
    send_batch_max_size: 1500
    timeout: 10s
exporters:  
  otlp/log:  
    endpoint: http://10.20.10.4:3301
    tls:  
      insecure: true
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [ otlp/log ]`

And im receiving grpc error
      
```
 2024-05-21T21:20:10.481Zwarnzapgrpc/zapgrpc.go:195[core]` [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.20.10.4:3301", ServerName: "10.20.10.4:3301", }.
 Err: connection error: desc = "error reading server preface: http2: frame too large"{"grpc_log": true}
```
 
 is there quick fix to this error . I tried to use http rather than grpc but didnt work

**Comment by prashant-shahi** [comment]
`3301` port is not the correct ingestion endpoint.

You can use either of the following (supported based on the SDK/collector):
- gRPC: `4317`
- HTTP: `4318`
