### ISSUE TITLE
Check impact of keeping cache size to 1M or 100M in signozspanmetricsprocessor

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#41]
<a href="https://github.com/ankitnayan"><img src="https://avatars.githubusercontent.com/u/12460410?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ankitnayan](https://github.com/ankitnayan)**
_Monday Jul 11, 2022 at 12:09 GMT_
_Originally opened as https://github.com/SigNoz/opentelemetry-collector-contrib/issues/1851_

----

It is not possible to determine the cache size beforehand as users keep on adding services to signoz. We should have an idea of the impact of keeping a high number for `dimensions_cache_size` like `1M` or `100M`. Or should we change the size dynamically based on some metric/number?

**Comment by srikanthccv** [comment]
<a href="https://github.com/srikanthccv"><img src="https://avatars.githubusercontent.com/u/22846633?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [srikanthccv](https://github.com/srikanthccv)**
_Monday Jul 18, 2022 at 12:31 GMT_

----

This number is probably way too big even for the large scale. The metrics processors receives the data as it arrives and computes the metric values. Each metric maintains it's own cache so there is no chance of one interfering other. The `pdata` received should be really big and diverse to hit the cache size issue. Let's look at the callCache since that dominates here. 

The size should only be big enough to accommodate the keys prepared in `aggregateMetircs` to be available while `buildMetrics`. The label set included is {service_name, span_name, status_code, span_kind, htt_status_code}. The simple resource spans object should have the data around {10 services, 15 ops, all 5 span kinds, all 3 status codes, 5 http codes} (not the overall but just the single process call) `pdata.Traces` to reach the current limit of this processor. In reality this doesn't happen because data sent by service is processed as it arrives. If there were an error and key is missing then there should be span data drop too because we don't continue in the case of failure. Even if 5x the both the services and operations we will still have lot of room left. Again this not for the overall data but just the data processor receives in each call. IMO this is very unlikely to happen.

**Comment by ankitnayan** [comment]
- [ ] check if higher value like 100K takes up memory during boot or will it be occupied based on the usage? And accordingly we can choose if we can enable higher value as default config for small users also.
- [ ] enable loggers to print some cardinality/metrics suggestions when `key` not found issue is caught. Using this users should be able to understand and ask suggestions from us
- [ ] enable dropping some metrics based on rules in spanmetricsprocessor to control cache blow up

**Comment by srikanthccv** [comment]
> check if higher value like 100K takes up memory during boot or will it be occupied based on the usage

No memory allocation at the initialisation; it is dynamic https://github.com/hashicorp/golang-lru/blob/master/simplelru/list.go. 

> And accordingly we can choose if we can enable higher value as default config for small users also.

I think this should be done by the users themselves. By setting it to a large value as a default it is prone to memory issues and most users prefer the dropping rather than crashes. If they wish to increase they would appropriately setup based on their resources.

> enable loggers to print some cardinality/metrics suggestions when key not found issue is caught. 

> enable dropping some metrics based on rules in spanmetricsprocessor to control cache blow up

Please take a look at https://github.com/SigNoz/signoz-otel-collector/pull/49, it logs the cardinality for each attribute and allows to ignore certain patterns on them.

**Comment by ankitnayan** [comment]
>I think this should be done by the users themselves. 

Okay..then we should mention this in docs (maybe production readiness docs?). Also, suggesting to increase the default value of `dimension_cache` to 100K. I am expecting around 2K-5K metrics of 1 service on avg. So, 10K seems very less for that. What do you say?

**Comment by srikanthccv** [comment]
Sure, 100k is a reasonable size for many users.
