### ISSUE TITLE
Ingest host's systemd journald logs

### ISSUE THREAD

**Issue by davispuh** [SigNoz/signoz-otel-collector#431]
I want to ingest logs from host systemd journald.

Any ideas how to accomplish this?

There is `Journald Receiver` => https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/journaldreceiver
but it needs `journalctl` which is not present in Alpine Docker image.

Also it doesn't look like systemd/journald has been packaged for Alpine so would need to build it from source which seems very complicated and additional maintenance burden.

What about switching current Alpine base image to some other like Debian which would have `journalctl` ?
Any other ideas?

**Comment by srikanthccv** [comment]
You could run the collector binary and forward the logs to the main SigNoz installation?

**Comment by davispuh** [comment]
That doesn't seem ideal because collector is not packaged for distributions.
That means I need to either build/package it myself or extract it from collector Docker image
In both cases it's additional maintenance burden for me to keep it updated.

I also found another way, there is [systemd-netlogd](https://github.com/systemd/systemd-netlogd) that can forward journal to remote Syslog. In which case I would run it on host and forward to OTel [Syslog Reciever](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver).


I think ideal case would be if at same time when you build Docker image you would also create Distro packages which people could use aswell.

Let's say if I package collector for few distributions would you accept such PR and distribute those packages?

**Comment by davispuh** [comment]
Oh indeed, I didn't think of this.

So yes the solution is:
1. Install OpenTelemetry Collector on host (it is packaged for most distributions on their GitHub)
2. Use Journald Receiver
3. Use OTLP Exporter to export to SigNoz Collector
