### ISSUE TITLE
Do not write the tag_attributes/span_attributes tables if the number or unique values is above 25k

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#467]
Free-form text attributes where every value is unique offer little practical value for storage or suggestions. When each entry is different from all others, maintaining these attributes or trying to generate recommendations becomes meaningless.

**Comment by ankitnayan** [comment]
I agree to this. What would be the logic of implementation? Will the decision be made at the collector after doing some analysis on CH for attributes? It would be great if we can keep a few samples of the values for better UX but not necessarily

**Comment by srikanthccv** [comment]
> What would be the logic of implementation? Will the decision be made at the collector after doing some analysis on CH for attributes?

Yes, the implementation would run a go routine periodically to fetch the distinct count of keys ingested from `signoz_logs.distributed_tag_attributes` and `signoz_traces.distributed_span_attributes`, next time all the keys that exceed the threshold will be skipped. To clarify my proposal is to apply these checks attributes of span/log, but not for the resource attribute gets ingested because they are usually controlled at the source. The additional condition that I believe we should apply is regardless of the distinct count, if a string value exceeds 256 (configurable) characters, they should also be skipped because there is no real-world scenario I can think of where people maintain such a lenghy enums/values that would make sense in suggestions.

> It would be great if we can keep a few samples of the values for better UX but not necessarily

I am not sure if it's going to be better UX if we consider all steps, imagine it suggested some values, but when you try to filter the search by typing something, no results show up because not all values are retained, it can confuse the user if the values exist or not. IMO, we should not show any suggestions for such keys (similar to what we do for the body). It should be either we fully retain all values and suggest (current status) or don't suggest anything (this issue).

**Comment by ankitnayan** [comment]
okay... all of these makes sense
