### ISSUE TITLE
Build and push on merge

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#7]
The changes that get merged onto develop branch are usually required for dependent PRs in the main repo. The `image:dev` should be pushed so that changes are in sync and the main application works without any issue.

**Comment by prashant-shahi** [comment]
Let's use `develop` tag to keep it consistent with other repos

**Comment by srikanthccv** [comment]
Sure, I just used it as an example. You can write up the versioning and releasing strategy and we can follow that.
