### ISSUE TITLE
(logs): store the resource attributes separately

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#96]
I believe this is already done for logs. Verify once and close.

**Comment by nityanandagohain** [comment]
Yes we have a separate column for https://github.com/SigNoz/signoz-otel-collector/blob/86419af414a055ee93ed0d2bfeb60a7a3301dcd0/exporter/clickhouselogsexporter/migrations/000001_init_db.up.sql#L13

https://github.com/SigNoz/signoz-otel-collector/blob/86419af414a055ee93ed0d2bfeb60a7a3301dcd0/exporter/clickhouselogsexporter/migrations/000001_init_db.up.sql#L36


is this what you asked ?
